drop table FA_AUDIT_TRAILS cascade constraints;

 CREATE TABLE FA_AUDIT_TRAILS 
   (	AT_SEQ_NO NUMBER(16,0) NOT NULL ENABLE, 
	AT_TRXN_TYPE VARCHAR2(100 ) NOT NULL ENABLE, 
	AT_OLD_DATA VARCHAR2(100 ), 
	AT_NEW_DATA VARCHAR2(100 ), 
	ENT_DATE DATE, 
	MOD_DATE DATE, 
	AT_USER VARCHAR2(100 ) NOT NULL ENABLE, 
	TABLE_NAME VARCHAR2(500 ), 
	 CONSTRAINT AT_SEQ_NO_PK PRIMARY KEY (AT_SEQ_NO)
   ) ;

drop public synonym FA_AUDIT_TRAILS;

create public synonym FA_AUDIT_TRAILS for FA_AUDIT_TRAILS;