drop table FA_BANK_BRANCH cascade constraints;

CREATE TABLE FA_BANK_BRANCH 
   (	BANK_ID NUMBER NOT NULL ENABLE, 
	BANK_BRANCH_ID NUMBER NOT NULL ENABLE, 
	BANK_BRANCH_NAME VARCHAR2(500 ) NOT NULL ENABLE, 
	CO_DELETED NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT FA_BANK_BRANCH_PK PRIMARY KEY (BANK_ID, BANK_BRANCH_ID)
   );

   COMMENT ON COLUMN FA_BANK_BRANCH.CO_DELETED IS '0 IS NOT DELETED , 1 IS DELETED';

drop public synonym FA_BANK_BRANCH;

create public synonym FA_BANK_BRANCH for FA_BANK_BRANCH;