 
drop table FA_COMP_DEPENDENTS cascade constraints;

  CREATE TABLE FA_COMP_DEPENDENTS 
   (	EMP_ID NUMBER NOT NULL ENABLE, 
	DETAILS_ID NUMBER NOT NULL ENABLE, 
	TAX_YEAR NUMBER NOT NULL ENABLE, 
	DEPENDENTS_NAME VARCHAR2(500 ) NOT NULL ENABLE, 
	DEPENDENTS_DESC VARCHAR2(500 ) NOT NULL ENABLE, 
	DEPENDENTS_IDENTIFIED VARCHAR2(500 ) NOT NULL ENABLE, 
	DEPENDENTS_NATIONALITY NUMBER NOT NULL ENABLE, 
	DEPENDENTS_BIRTHDATE VARCHAR2(50 ) NOT NULL ENABLE, 
	DELETED NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT FA_COMP_DEPENDENTS_PK PRIMARY KEY (EMP_ID, DETAILS_ID, TAX_YEAR)
   );

   COMMENT ON COLUMN FA_COMP_DEPENDENTS.DELETED IS '0 IS not deleted , 1 is Deleted';


drop public synonym FA_COMP_DEPENDENTS;

create public synonym FA_COMP_DEPENDENTS for FA_COMP_DEPENDENTS;