 
drop table FA_CHART_OF_ACCOUNTS cascade constraints;

  CREATE TABLE FA_CHART_OF_ACCOUNTS 
   (	CFA_ID NUMBER NOT NULL ENABLE, 
	CFA_NUMBER NUMBER NOT NULL ENABLE, 
	CFA_NAME VARCHAR2(1000) NOT NULL ENABLE, 
	CFA_PAIRENT NUMBER, 
        ACCOUNT_CONNECTEDBY NUMBER,
	 CONSTRAINT FA_CHART_OF_ACCOUNTS_PK PRIMARY KEY (CFA_ID), 
	 CONSTRAINT FA_CHART_OF_ACCOUNTS_UK1 UNIQUE (CFA_NUMBER)
   ) ;


drop public synonym FA_CHART_OF_ACCOUNTS;

create public synonym FA_CHART_OF_ACCOUNTS for FA_CHART_OF_ACCOUNTS;