 
drop table FA_COMP_EMP_SAL_TAX_DETAILS cascade constraints;

    CREATE TABLE FA_COMP_EMP_SAL_TAX_DETAILS 
   (	EMP_ID NUMBER NOT NULL ENABLE, 
	DETAILS_ID NUMBER NOT NULL ENABLE, 
	TAX_YEAR NUMBER NOT NULL ENABLE, 
	INDIVIDUAL_MERGE NUMBER DEFAULT 0 NOT NULL ENABLE, 
	WIFE_WORK_STATUS NUMBER, 
	WIFE_NAME VARCHAR2(2000 ), 
	WIFE_NATIONALITY_ID VARCHAR2(100 ), 
	WIFE_TAX_ACCOUNT_NO VARCHAR2(100 ), 
	WIFE_AGREE_FILE VARCHAR2(2000 ), 
	EMP_ANNUAL_SALARY NUMBER DEFAULT 0 NOT NULL ENABLE, 
	EMP_ANNUAL_SALARY_ATTACH VARCHAR2(500 ), 
	WIFE_ANNUAL_SALARY NUMBER DEFAULT 0 NOT NULL ENABLE, 
	WIFE_ANNUAL_SALARY_ATTACH VARCHAR2(500 ), 
	TOTAL_RETIREMENT NUMBER DEFAULT 0 NOT NULL ENABLE, 
	TOTAL_RETIREMENT_ATTACH VARCHAR2(500 ), 
	COUNT_DISABLED_CHILDREN NUMBER DEFAULT 0 NOT NULL ENABLE, 
	COUNT_DISABLED_CHILDREN_ATTACH VARCHAR2(500 ), 
	ANNUAL_EMP_EXPENSES NUMBER DEFAULT 0 NOT NULL ENABLE, 
	ANNUAL_EMP_EXPENSES_ATTACH VARCHAR2(500 ), 
	ANNUAL_WIFE_EXPENSES NUMBER DEFAULT 0 NOT NULL ENABLE, 
	ANNUAL_WIFE_EXPENSES_ATTACH VARCHAR2(500 ), 
	C_1_LEARNING_EXPENSE NUMBER DEFAULT 0 NOT NULL ENABLE, 
	C_1_LEARNING_EXPENSE_ATTACH VARCHAR2(500 ), 
	C_2_LEARNING_EXPENSE NUMBER DEFAULT 0 NOT NULL ENABLE, 
	C_2_LEARNING_EXPENSE_ATTACH VARCHAR2(500 ), 
	C_3_LEARNING_EXPENSE NUMBER DEFAULT 0 NOT NULL ENABLE, 
	C_3_LEARNING_EXPENSE_ATTACH VARCHAR2(500 ), 
	COUNT_DEPENDENTS NUMBER DEFAULT 0 NOT NULL ENABLE, 
	COUNT_DEPENDENTS_ATTACH VARCHAR2(500 ), 
	DONATIONS_TO_GOVERNMENT NUMBER DEFAULT 0 NOT NULL ENABLE, 
	DONATIONS_TO_GOVERNMENT_ATTACH VARCHAR2(500 ), 
	DONATIONS_SOCIAL NUMBER DEFAULT 0 NOT NULL ENABLE, 
	DONATIONS_SOCIAL_ATTACH VARCHAR2(500 ), 
	SALARY_DEDUCTIONS NUMBER DEFAULT 0 NOT NULL ENABLE, 
	SALARY_DEDUCTIONS_ATTACH VARCHAR2(500 ), 
	CAR_CUSTOMS_FEES NUMBER DEFAULT 0 NOT NULL ENABLE, 
	CAR_CUSTOMS_FEES_ATTACH VARCHAR2(500 ), 
	RETIREMENT_DEDUCTIONS NUMBER DEFAULT 0 NOT NULL ENABLE, 
	RETIREMENT_DEDUCTIONS_ATTACH VARCHAR2(500 ), 
	REQUDATE DATE DEFAULT sysdate NOT NULL ENABLE, 
	TOTAL_339 NUMBER, 
	TOTAL_3303 NUMBER, 
	TOTAL_3307 NUMBER, 
	TOTAL_99310 NUMBER, 
	TOTAL_993104 NUMBER, 
	TOTAL_9027 NUMBER, 
	TOTAL_9028 NUMBER, 
	TOTAL_9029 NUMBER, 
	TOTAL_99110 NUMBER, 
	TOTAL_99130 NUMBER, 
	TOTAL_99510 NUMBER, 
	TOTAL_991201 NUMBER, 
	SAL_TAX_NEED NUMBER, 
	INCOM_FILE VARCHAR2(2000 ), 
	DELETED NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT FA_COMP_EMPTAX_DETAILS_PK PRIMARY KEY (EMP_ID, DETAILS_ID, TAX_YEAR)
   );

   COMMENT ON COLUMN FA_COMP_EMP_SAL_TAX_DETAILS.DELETED IS '0 IS not deleted , 1 is Deleted';


drop public synonym FA_COMP_EMP_SAL_TAX_DETAILS;

create public synonym FA_COMP_EMP_SAL_TAX_DETAILS for FA_COMP_EMP_SAL_TAX_DETAILS;