 
drop table FA_CUSTOMER_CHART_OF_ACCOUNT cascade constraints;


  CREATE TABLE FA_CUSTOMER_CHART_OF_ACCOUNT 
   (	CUSTOMER_ID NUMBER NOT NULL ENABLE, 
	ACCOUNT_NUMBER NUMBER, 
	ACCOUNT_NAME VARCHAR2(500 ) NOT NULL ENABLE, 
	ACCOUNT_PAIRENT NUMBER, 
	ACCOUNT_CONNECTEDBY NUMBER, 
	 CONSTRAINT FA_CUSTOMER_ACCOUNT_PK PRIMARY KEY (CUSTOMER_ID, ACCOUNT_NAME)
   )  ;

drop public synonym FA_CUSTOMER_CHART_OF_ACCOUNT;

create public synonym FA_CUSTOMER_CHART_OF_ACCOUNT for FA_CUSTOMER_CHART_OF_ACCOUNT;