 
drop table FA_CUSTOMER_COMP cascade constraints;

  CREATE TABLE FA_CUSTOMER_COMP 
   (	CC_ID NUMBER NOT NULL ENABLE, 
	CC_CUSTOMER_NAME VARCHAR2(100 ) NOT NULL ENABLE, 
	CC_CUSTOMER_NATIO NUMBER, 
	CC_CUSTOMER_DOCTYPE NUMBER NOT NULL ENABLE, 
	CC_CUSTOMER_DOCTYPENO VARCHAR2(50 ) NOT NULL ENABLE, 
	CC_CUSTOMER_FILE VARCHAR2(2000 ), 
	CC_CUSTOMER_MOBILE VARCHAR2(20 ) NOT NULL ENABLE, 
	CC_COMP_TYPE NUMBER NOT NULL ENABLE, 
	CC_COMP_SUBTYPE NUMBER NOT NULL ENABLE, 
	CC_COMP_NAME VARCHAR2(500 ) NOT NULL ENABLE, 
	CC_COMP_ESTABLISH_DATE DATE NOT NULL ENABLE, 
	CC_COMP_COMER_NO VARCHAR2(20 ) NOT NULL ENABLE, 
	CC_COM_TAX_NO VARCHAR2(20 ) NOT NULL ENABLE, 
	CC_COMP_NATIO_ID VARCHAR2(20 ) NOT NULL ENABLE, 
	CC_COMP_MONEY_CAPITAL NUMBER NOT NULL ENABLE, 
	CC_COMP_ADDRESS VARCHAR2(200 ) NOT NULL ENABLE, 
	CC_COMP_PHONE VARCHAR2(20 ) NOT NULL ENABLE, 
	CC_COMP_EMAIL VARCHAR2(50 ) NOT NULL ENABLE,
        SECTOR_ID number,
        SALES_TAXABLE number,
        EHLAK_STATUS number,
        ACTIVITES_STATUS number,
        KEEPING_ACCOUNT_STATUS number,
	CC_COMP_SPECIALIZATION VARCHAR2(2000 ) NOT NULL ENABLE, 
	CC_DELEGATENAME VARCHAR2(200 ), 
	CC_DELETED NUMBER DEFAULT 0 NOT NULL ENABLE, 
	CC_DELEGATECATEGORY VARCHAR2(1000 ), 
        Sector_ID NUMBER ,
	 CONSTRAINT FA_CUSTOMER_COMP_PK PRIMARY KEY (CC_ID)
   );

   COMMENT ON COLUMN FA_CUSTOMER_COMP.SALES_TAXABLE IS '1 is Taxable,2 is not Taxable';
   COMMENT ON COLUMN FA_CUSTOMER_COMP.EHLAK_STATUS IS '1 is need Ehlak,2 is not need Ehlak';
   COMMENT ON COLUMN FA_CUSTOMER_COMP.ACTIVITES_STATUS IS '1 have Activites, 2 have not activites';

   COMMENT ON COLUMN FA_CUSTOMER_COMP.CC_DELETED IS '0 IS NOT DELETED , 1 IS DELETED';


drop public synonym FA_CUSTOMER_COMP;

create public synonym FA_CUSTOMER_COMP for FA_CUSTOMER_COMP;