 
drop table FA_CUSTOMER_ASSESTS cascade constraints;

  
  CREATE TABLE FA_CUSTOMER_ASSESTS 
   (	CA_ID NUMBER NOT NULL ENABLE, 
	CA_CUSTOMER_ID NUMBER NOT NULL ENABLE, 
	CA_ASSEST_ACCOUNT_NUMBER NUMBER NOT NULL ENABLE, 
	CA_ASSEST_NAME VARCHAR2(1000 ) NOT NULL ENABLE, 
	CA_ASSEST_COST_WITH_TAX NUMBER NOT NULL ENABLE, 
	CA_TAX_PERSANTAGE NUMBER NOT NULL ENABLE, 
	CA_COUNT NUMBER NOT NULL ENABLE,  
	CA_ASSEST_WORKING_DATE VARCHAR2(100 ) NOT NULL ENABLE, 
	CA_INVOICE_NUMBER VARCHAR2(100 ) NOT NULL ENABLE, 
	CA_INVOICE_DATE VARCHAR2(100 ) NOT NULL ENABLE, 
	CA_ROCURMENT_TYPE NUMBER NOT NULL ENABLE, 
	CA_SUPPLIER_NUMBER NUMBER NOT NULL ENABLE, 
	CA_ELHALKPERCANTAGE NUMBER, 
	CA_EHLAKACCOUNT NUMBER, 
	CA_COMPLEXEHLAKACCOUNT NUMBER, 
	CA_ATTACHMENT VARCHAR2(500 ), 
        CA_TAXABLE  NUMBER, 
        CA_ACTIVE   NUMBER, 
	 CONSTRAINT FA_CUSTOMER_ASSESTS_PK PRIMARY KEY (CA_ID, CA_CUSTOMER_ID)
   ) ;



drop public synonym FA_CUSTOMER_ASSESTS;

create public synonym FA_CUSTOMER_ASSESTS for FA_CUSTOMER_ASSESTS;