 
drop table FA_COMP_AGREMENT_PAYMENT cascade constraints;

  CREATE TABLE FA_COMP_AGREMENT_PAYMENT 
   (	AGP_ID NUMBER NOT NULL ENABLE, 
	AG_ID NUMBER NOT NULL ENABLE, 
	CUSTOMER_ID NUMBER NOT NULL ENABLE, 
	TOTAL_AMOUNT NUMBER NOT NULL ENABLE, 
	PAYMENT_STATUS NUMBER DEFAULT 0 NOT NULL ENABLE
   ) ;

   COMMENT ON COLUMN FA_COMP_AGREMENT_PAYMENT.PAYMENT_STATUS IS '0 IS not Completed , 1 is Completed';


drop public synonym FA_COMP_AGREMENT_PAYMENT;

create public synonym FA_COMP_AGREMENT_PAYMENT for FA_COMP_AGREMENT_PAYMENT;