 
drop table FA_CO_AGREMENT_PAY_DETAILS cascade constraints;

 CREATE TABLE FA_CO_AGREMENT_PAY_DETAILS 
   (	AGP_ID NUMBER NOT NULL ENABLE, 
	VOUCHER_NO NUMBER NOT NULL ENABLE, 
	VOUCHER_DATE DATE NOT NULL ENABLE, 
	VOUCHER_AMOUNT NUMBER NOT NULL ENABLE, 
	VOUCHER_DESC VARCHAR2(1000) NOT NULL ENABLE, 
	PAYMENT_TYPE NUMBER NOT NULL ENABLE, 
	CHEQUE_NO NUMBER, 
	BANK_ID NUMBER, 
	RECIPT_NAME VARCHAR2(2000) NOT NULL ENABLE
   ) ;

   COMMENT ON COLUMN FA_CO_AGREMENT_PAY_DETAILS.PAYMENT_TYPE IS '1 IS Chash , 2 is Cheque';


drop public synonym FA_CO_AGREMENT_PAY_DETAILS;

create public synonym FA_CO_AGREMENT_PAY_DETAILS for FA_CO_AGREMENT_PAY_DETAILS;