 
drop table FA_COMPAGREMENT cascade constraints;

   
  CREATE TABLE FA_COMPAGREMENT 
   (	AG_ID NUMBER NOT NULL ENABLE, 
	CUSTOMER_ID NUMBER NOT NULL ENABLE, 
	FXG_ID NUMBER NOT NULL ENABLE, 
	AG_AGREMENTDATE DATE NOT NULL ENABLE, 
	AG_CONTRATETIME NUMBER NOT NULL ENABLE, 
	AG_YEARORMONTH NUMBER NOT NULL ENABLE, 
	AG_TOTALPRICE NUMBER NOT NULL ENABLE, 
	AG_ONSING NUMBER NOT NULL ENABLE, 
	AG_PAYMENTCOUNT NUMBER NOT NULL ENABLE, 
	AG_TIRMINATECONTRACTDAYS NUMBER NOT NULL ENABLE, 
	AG_NOTES VARCHAR2(1000 ) NOT NULL ENABLE, 
	AG_AGRMENTWRITENDATE DATE NOT NULL ENABLE, 
	AG_DELETED NUMBER DEFAULT 0 NOT NULL ENABLE, 
	CONTRACT_FILE VARCHAR2(2000 ), 
	CONTRACT_SIGNED NUMBER DEFAULT 0, 
	AG_CONTRACT_END_DATE DATE, 
	CONTRACT_STATUS NUMBER DEFAULT 1, 
        VOUCHER_FILE VARCHAR2(2000 ),
	 CONSTRAINT FA_COMPAGREMEN_PK PRIMARY KEY (AG_ID)
   );

   COMMENT ON COLUMN FA_COMPAGREMENT.AG_DELETED IS '0 IS NOT DELETED , 1 IS DELETED';
   COMMENT ON COLUMN FA_COMPAGREMENT.CONTRACT_SIGNED IS '0 not signed , 1 signed';
   COMMENT ON COLUMN FA_COMPAGREMENT.CONTRACT_STATUS IS '1 wait for singed,2 active,3 Ended,4 Tirminated';



drop public synonym FA_COMPAGREMENT;

create public synonym FA_COMPAGREMENT for FA_COMPAGREMENT;