 
drop table FA_COMPAGREMENTSERVICES cascade constraints;

  CREATE TABLE FA_COMPAGREMENTSERVICES 
   (	AG_ID NUMBER NOT NULL ENABLE, 
	SERVICE_ID NUMBER NOT NULL ENABLE, 
	AGS_DELETED NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT FA_COMPAGREMENTSERVICES_PK PRIMARY KEY (AG_ID, SERVICE_ID)
   );

   COMMENT ON COLUMN FA_COMPAGREMENTSERVICES.AGS_DELETED IS '0 IS NOT DELETED , 1 IS DELETED';

drop public synonym FA_COMPAGREMENTSERVICES;

create public synonym FA_COMPAGREMENTSERVICES for FA_COMPAGREMENTSERVICES;