 
drop table FA_FIX_AGREMENT cascade constraints;

CREATE TABLE FA_FIX_AGREMENT 
   (	FXG_ID NUMBER NOT NULL ENABLE, 
	FXG_COMP_NAME VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_COMP_LOGO VARCHAR2(1000 ), 
	FXG_COMP_ADDRESS VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_REPRENTER_NAME VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_COMP_DESC VARCHAR2(2000 ) NOT NULL ENABLE, 
	FXG_ITEM1 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM2 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM3 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM4 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM5 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM6 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM7 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM8 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM9 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM10 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM11 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM12 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM13 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM14 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_ITEM15 VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_FOOTER VARCHAR2(1000 ) NOT NULL ENABLE, 
	FXG_DELETED NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT FA_FIX_AGREMENT_PK PRIMARY KEY (FXG_ID)
   );

   COMMENT ON COLUMN FA_FIX_AGREMENT.FXG_DELETED IS '0 IS NOT DELETED , 1 IS DELETED';

drop public synonym FA_FIX_AGREMENT;

create public synonym FA_FIX_AGREMENT for FA_FIX_AGREMENT;