 
drop table FA_JOURNAL_DETAILS cascade constraints;

  CREATE TABLE FA_JOURNAL_DETAILS 
   (	JOR_ID NUMBER NOT NULL ENABLE, 
	JOR_CUSTOMER_ID NUMBER NOT NULL ENABLE, 
	JOR_DETAIL_ID NUMBER NOT NULL ENABLE, 
	JOR_ACCOUNTNO VARCHAR2(500 ) NOT NULL ENABLE, 
	JOR_DEPIT_AMOUNT NUMBER DEFAULT 0 NOT NULL ENABLE, 
	JOR_CREDIT_AMOUNT NUMBER DEFAULT 0 NOT NULL ENABLE, 
	JOR_TAX_PERSANTAGE NUMBER, 
	 CONSTRAINT FA_JOURNAL_DETAILS_PK PRIMARY KEY (JOR_ID, JOR_CUSTOMER_ID, JOR_DETAIL_ID)
   );

drop public synonym FA_JOURNAL_DETAILS;

create public synonym FA_JOURNAL_DETAILS for FA_JOURNAL_DETAILS;