 
drop table FA_JOURNAL cascade constraints;

  CREATE TABLE FA_JOURNAL 
   (	JOR_ID NUMBER NOT NULL ENABLE, 
	JOR_CUSTOMER_ID NUMBER NOT NULL ENABLE, 
	JOR_DATE DATE NOT NULL ENABLE, 
	JOR_DESC VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	JOR_INVOICE_ID number, 
	JOR_INVOICE_DATE DATE, 
	JOR_ATTACHMENT VARCHAR2(500 BYTE), 
	JOR_PAID_TYPE VARCHAR2(20 BYTE), 
	 CONSTRAINT FA_JOURNAL_PK PRIMARY KEY (JOR_ID, JOR_CUSTOMER_ID)
   );

   COMMENT ON COLUMN FA_JOURNAL.JOR_PAID_TYPE IS '1 Cash,2 Bank, 3 PostPaid';

drop public synonym FA_JOURNAL;

create public synonym FA_JOURNAL for FA_JOURNAL;