 
drop table FA_SYSTEM_USER_PRIVILEGE cascade constraints;


  CREATE TABLE FA_SYSTEM_USER_PRIVILEGE 
   (	SUP_ID NUMBER NOT NULL ENABLE, 
	SU_ID NUMBER NOT NULL ENABLE, 
	SFG_ID NUMBER NOT NULL ENABLE, 
	SUP_DELETED NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT FA_SYSTEM_USER_PRIVILEGE_PK PRIMARY KEY (SUP_ID), 
	 CONSTRAINT FA_SYSTEM_USER_PRIVILEGE_UK1 UNIQUE (SU_ID, SFG_ID), 
	 CONSTRAINT FA_USER_PRIVILEGE_USER_FK FOREIGN KEY (SU_ID)
	  REFERENCES FA_SYSTEM_USERS (SU_USER_ID) ENABLE
   );

   COMMENT ON COLUMN FA_SYSTEM_USER_PRIVILEGE.SUP_DELETED IS 'O IS NOT DELETED , 1 IS DELETED';


drop public synonym FA_SYSTEM_USER_PRIVILEGE;

create public synonym FA_SYSTEM_USER_PRIVILEGE for FA_SYSTEM_USER_PRIVILEGE;