 
drop table FA_SYSTEM_SUBG_FORM cascade constraints;

CREATE TABLE FA_SYSTEM_SUBG_FORM 
   (	SSGF_ID NUMBER NOT NULL ENABLE, 
	SSGF_SUB_G_ID NUMBER NOT NULL ENABLE, 
	SSGF_FORM_ID NUMBER NOT NULL ENABLE, 
	SSGF_DELETED NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT FA_SYSTEM_SUBG_FORM_PK PRIMARY KEY (SSGF_ID, SSGF_SUB_G_ID, SSGF_FORM_ID), 
	 CONSTRAINT FA_SUBG_FORM_FK1 FOREIGN KEY (SSGF_FORM_ID)
	  REFERENCES FA_SYSTEM_FORMS (SF_ID) ENABLE, 
	 CONSTRAINT FA_SUBG_SUBGROUP_FK FOREIGN KEY (SSGF_SUB_G_ID)
	  REFERENCES FA_SYSTEM_SUB_GROUP (SSG_ID) ENABLE
   );

   COMMENT ON COLUMN FA_SYSTEM_SUBG_FORM.SSGF_DELETED IS '0 IS NOT DELETED,1 IS DELETED';

drop public synonym FA_SYSTEM_SUBG_FORM;

create public synonym FA_SYSTEM_SUBG_FORM for FA_SYSTEM_SUBG_FORM;