 
drop table FA_SYSTEM_GROUPS cascade constraints;

CREATE TABLE FA_SYSTEM_GROUPS 
   (	SG_ID NUMBER NOT NULL ENABLE, 
	SG_GROUP_NAME VARCHAR2(200 ) NOT NULL ENABLE, 
	SG_GROUP_TITLE VARCHAR2(20 ), 
	SG_GROUP_INDEX NUMBER NOT NULL ENABLE, 
	SG_GROUP_DELETED NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT FA_SYSTEM_GROUPS_PK PRIMARY KEY (SG_ID)
   );

   COMMENT ON COLUMN FA_SYSTEM_GROUPS.SG_GROUP_DELETED IS '0 IS NOT DELETED, 1 IS DELETED';


drop public synonym FA_SYSTEM_GROUPS;

create public synonym FA_SYSTEM_GROUPS for FA_SYSTEM_GROUPS;