 
drop table FA_SALARY_TAX_SLICE cascade constraints;


  CREATE TABLE FA_SALARY_TAX_SLICE 
   (	SLICE_ID NUMBER NOT NULL ENABLE, 
	SLICE_AMOUNT NUMBER NOT NULL ENABLE, 
	SLICE_PERCANTAGE NUMBER NOT NULL ENABLE, 
	SLICE_FROM_YEAR NUMBER NOT NULL ENABLE, 
	SLICE_TO_YEAR NUMBER
   );



drop public synonym FA_SALARY_TAX_SLICE;

create public synonym FA_SALARY_TAX_SLICE for FA_SALARY_TAX_SLICE;