 
drop table FA_SEND_EMAILS cascade constraints;


 CREATE TABLE FA_SEND_EMAILS 
   (	CUSTOMER_ID NUMBER NOT NULL ENABLE, 
	MAIL_MESSAGE_ID NUMBER NOT NULL ENABLE, 
	SEND_STATUS NUMBER DEFAULT 0 NOT NULL ENABLE, 
	SEND_DATE DATE
   ) ;

   COMMENT ON COLUMN FA_SEND_EMAILS.SEND_STATUS IS '0 IS NOT send , 1 IS sent';


drop public synonym FA_SEND_EMAILS;

create public synonym FA_SEND_EMAILS for FA_SEND_EMAILS;