 
drop table FA_SALARY_EXEMPTION_YEAR cascade constraints;

CREATE TABLE FA_SALARY_EXEMPTION_YEAR 
   (	EXEMPTION_FROM_YEAR NUMBER NOT NULL ENABLE, 
	EXEMPTION_TO_YEAR NUMBER, 
	EXEMPTION_AMOUNT NUMBER NOT NULL ENABLE, 
	DISABLEDAMOUNT NUMBER NOT NULL ENABLE
   );
drop public synonym FA_SALARY_EXEMPTION_YEAR;

create public synonym FA_SALARY_EXEMPTION_YEAR for FA_SALARY_EXEMPTION_YEAR;