 
drop table FA_SYSTEM_FTP cascade constraints;

  CREATE TABLE FA_SYSTEM_FTP 
   (	FTP_LINK VARCHAR2(500 ) NOT NULL ENABLE, 
	FTP_USER VARCHAR2(500 ) NOT NULL ENABLE, 
	FTP_PASSWORD VARCHAR2(500 ) NOT NULL ENABLE, 
	 CONSTRAINT FA_SYSTEM_FTP_PK PRIMARY KEY (FTP_LINK, FTP_USER, FTP_PASSWORD)
   );

drop public synonym FA_SYSTEM_FTP;

create public synonym FA_SYSTEM_FTP for FA_SYSTEM_FTP;