 
drop table FA_SYSTEM_SUB_GROUP cascade constraints;


  CREATE TABLE FA_SYSTEM_SUB_GROUP 
   (	SSG_ID NUMBER NOT NULL ENABLE, 
	SSG_NAME VARCHAR2(50 ) NOT NULL ENABLE, 
	SSG_IMAGE VARCHAR2(50 ) NOT NULL ENABLE, 
	SSG_TITLE VARCHAR2(100 ) NOT NULL ENABLE, 
	SSG_DELETED NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT FA_SYSTEM_SUB_GROUP_PK PRIMARY KEY (SSG_ID), 
	 CONSTRAINT FA_SYSTEM_SUB_GROUP_UK1 UNIQUE (SSG_TITLE)
   );

   COMMENT ON COLUMN FA_SYSTEM_SUB_GROUP.SSG_DELETED IS '0 IS NOT DELETED,1 IS DELETED';


drop public synonym FA_SYSTEM_SUB_GROUP;

create public synonym FA_SYSTEM_SUB_GROUP for FA_SYSTEM_SUB_GROUP;