 
drop table FA_SYSTEM_USERS cascade constraints;


  
  CREATE TABLE FA_SYSTEM_USERS 
   (	SU_USER_ID NUMBER NOT NULL ENABLE, 
	SU_A_NAME VARCHAR2(60 ) NOT NULL ENABLE, 
	SU_E_NAME VARCHAR2(60 ), 
	SU_STATUS VARCHAR2(1 ) DEFAULT 'a', 
	SU_LAST_LOGON_DATE DATE, 
	SU_USER_PASSWORD VARCHAR2(30 ) NOT NULL ENABLE, 
	SU_PASSWORD_CHANGE_DATE DATE, 
	SU_ENT_DATE DATE DEFAULT sysdate NOT NULL ENABLE, 
	SU_MOD_DATE DATE DEFAULT sysdate NOT NULL ENABLE, 
	SU_USER VARCHAR2(30 ) DEFAULT substr(user,1,30) NOT NULL ENABLE, 
	 CHECK (su_status  in ('a','s','d')) ENABLE, 
	 CONSTRAINT PFA_SYSTEM_USERS_01 PRIMARY KEY (SU_USER_ID), 
	 CONSTRAINT FA_SYSTEM_USERS_UK1 UNIQUE (SU_USER)
   );


drop public synonym FA_SYSTEM_USERS;

create public synonym FA_SYSTEM_USERS for FA_SYSTEM_USERS;