 
drop table FA_SYSTEM_FORM_GROUP cascade constraints;

   CREATE TABLE FA_SYSTEM_FORM_GROUP 
   (	SFG_ID NUMBER NOT NULL ENABLE, 
	SFG_GROUP_ID NUMBER NOT NULL ENABLE, 
	SFG_SUBGFORM_ID NUMBER NOT NULL ENABLE, 
	SFG_DELETED NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT FA_SYSTEM_FORM_GROUP_PK PRIMARY KEY (SFG_ID),
	 CONSTRAINT FA_SYSTEM_FORM_GROUP_FA_S_FK1 FOREIGN KEY (SFG_GROUP_ID)
	  REFERENCES FA_SYSTEM_GROUPS (SG_ID) ENABLE
   );

   COMMENT ON COLUMN FA_SYSTEM_FORM_GROUP.SFG_DELETED IS '0 IS NOT DELETED,1 IS DELETED';

drop public synonym FA_SYSTEM_FORM_GROUP;

create public synonym FA_SYSTEM_FORM_GROUP for FA_SYSTEM_FORM_GROUP;