 
drop table FA_SYSTEM_PARAMETERS cascade constraints;

CREATE TABLE FA_SYSTEM_PARAMETERS 
   (	SP_MAJOR VARCHAR2(3 ) NOT NULL ENABLE, 
	SP_MINOR NUMBER NOT NULL ENABLE, 
	SP_E_DESCRIPTION VARCHAR2(100 ) NOT NULL ENABLE, 
	SP_A_DESCRIPTION VARCHAR2(100 ) NOT NULL ENABLE, 
	SP_ENT_DATE DATE DEFAULT sysdate NOT NULL ENABLE, 
	SP_MOD_DATE DATE DEFAULT sysdate NOT NULL ENABLE, 
	SP_USER VARCHAR2(30 ) DEFAULT substr(user,1,30) NOT NULL ENABLE, 
	SP_DELETED NUMBER DEFAULT 0, 
	 CONSTRAINT FA_SYSTEM_PARAMETERS_PK PRIMARY KEY (SP_MAJOR, SP_MINOR)
   );

   COMMENT ON COLUMN FA_SYSTEM_PARAMETERS.SP_DELETED IS '0 IS NOT DELETED, 1 IS DELETED';
   
drop public synonym FA_SYSTEM_PARAMETERS;

create public synonym FA_SYSTEM_PARAMETERS for FA_SYSTEM_PARAMETERS;