 
drop table FA_TAX_ITEMS cascade constraints;


  CREATE TABLE FA_TAX_ITEMS 
   (	EST_TAX_ITEMS_ID NUMBER NOT NULL ENABLE, 
	EST_TAX_ITEMS_NUMBER NUMBER NOT NULL ENABLE, 
	EST_TAX_ITEMS_DESC VARCHAR2(3000 ) NOT NULL ENABLE, 
	EST_DELETED NUMBER DEFAULT 0 NOT NULL ENABLE
   );

   COMMENT ON COLUMN FA_TAX_ITEMS.EST_DELETED IS '0 IS not deleted , 1 is Deleted';



drop public synonym FA_TAX_ITEMS;

create public synonym FA_TAX_ITEMS for FA_TAX_ITEMS;