
Insert into FA_SYSTEM_USER_PRIVILEGE (SUP_ID,SU_ID,SFG_ID,SUP_DELETED) values (3,1,3,0);
Insert into FA_SYSTEM_USER_PRIVILEGE (SUP_ID,SU_ID,SFG_ID,SUP_DELETED) values (4,1,4,0);
Insert into FA_SYSTEM_USER_PRIVILEGE (SUP_ID,SU_ID,SFG_ID,SUP_DELETED) values (5,1,5,0);
Insert into FA_SYSTEM_USER_PRIVILEGE (SUP_ID,SU_ID,SFG_ID,SUP_DELETED) values (6,1,6,0);
Insert into FA_SYSTEM_USER_PRIVILEGE (SUP_ID,SU_ID,SFG_ID,SUP_DELETED) values (8,1,8,0);
Insert into FA_SYSTEM_USER_PRIVILEGE (SUP_ID,SU_ID,SFG_ID,SUP_DELETED) values (1,1,1,0);
Insert into FA_SYSTEM_USER_PRIVILEGE (SUP_ID,SU_ID,SFG_ID,SUP_DELETED) values (2,1,2,0);
Insert into FA_SYSTEM_USER_PRIVILEGE (SUP_ID,SU_ID,SFG_ID,SUP_DELETED) values (7,1,7,0);
Insert into FA_SYSTEM_USER_PRIVILEGE (SUP_ID,SU_ID,SFG_ID,SUP_DELETED) values (9,1,9,0);
