
Insert into FA_SYSTEM_GROUPS (SG_ID,SG_GROUP_NAME,SG_GROUP_TITLE,SG_GROUP_INDEX,SG_GROUP_DELETED) values (1,'tblAdmin','إدارة النظام',0,0);
Insert into FA_SYSTEM_GROUPS (SG_ID,SG_GROUP_NAME,SG_GROUP_TITLE,SG_GROUP_INDEX,SG_GROUP_DELETED) values (2,'tblEmployee','إدارة الموظفين',1,0);
Insert into FA_SYSTEM_GROUPS (SG_ID,SG_GROUP_NAME,SG_GROUP_TITLE,SG_GROUP_INDEX,SG_GROUP_DELETED) values (3,'tblCustomers','إدارة العملاء',3,0);
Insert into FA_SYSTEM_GROUPS (SG_ID,SG_GROUP_NAME,SG_GROUP_TITLE,SG_GROUP_INDEX,SG_GROUP_DELETED) values (4,'tblAdmin3','container',4,0);
Insert into FA_SYSTEM_GROUPS (SG_ID,SG_GROUP_NAME,SG_GROUP_TITLE,SG_GROUP_INDEX,SG_GROUP_DELETED) values (5,'ttb','test',2,0);
