
Insert into FA_SYSTEM_FORM_GROUP (SFG_ID,SFG_GROUP_ID,SFG_SUBGFORM_ID,SFG_DELETED) values (3,3,3,0);
Insert into FA_SYSTEM_FORM_GROUP (SFG_ID,SFG_GROUP_ID,SFG_SUBGFORM_ID,SFG_DELETED) values (4,1,4,0);
Insert into FA_SYSTEM_FORM_GROUP (SFG_ID,SFG_GROUP_ID,SFG_SUBGFORM_ID,SFG_DELETED) values (5,1,5,0);
Insert into FA_SYSTEM_FORM_GROUP (SFG_ID,SFG_GROUP_ID,SFG_SUBGFORM_ID,SFG_DELETED) values (6,3,6,0);
Insert into FA_SYSTEM_FORM_GROUP (SFG_ID,SFG_GROUP_ID,SFG_SUBGFORM_ID,SFG_DELETED) values (8,3,8,0);
Insert into FA_SYSTEM_FORM_GROUP (SFG_ID,SFG_GROUP_ID,SFG_SUBGFORM_ID,SFG_DELETED) values (1,1,1,0);
Insert into FA_SYSTEM_FORM_GROUP (SFG_ID,SFG_GROUP_ID,SFG_SUBGFORM_ID,SFG_DELETED) values (2,2,2,0);
Insert into FA_SYSTEM_FORM_GROUP (SFG_ID,SFG_GROUP_ID,SFG_SUBGFORM_ID,SFG_DELETED) values (7,3,7,0);
Insert into FA_SYSTEM_FORM_GROUP (SFG_ID,SFG_GROUP_ID,SFG_SUBGFORM_ID,SFG_DELETED) values (9,3,9,0);
